version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: